language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mistermur/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mistermur/docker-react npm run test